// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetImagesInFolder(arg1:string):Promise<Array<string>>;

export function LoadImage(arg1:string):Promise<string>;

export function OpenImageDialog():Promise<string>;
