// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetImagesInFolder(arg1) {
  return window['go']['main']['App']['GetImagesInFolder'](arg1);
}

export function LoadImage(arg1) {
  return window['go']['main']['App']['LoadImage'](arg1);
}

export function OpenImageDialog() {
  return window['go']['main']['App']['OpenImageDialog']();
}
